name: Deploy Flutter Web to gh-pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter (pin to your version)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.35.4"

      - name: Enable web & fetch deps
        run: |
          flutter config --enable-web
          flutter pub get

      - name: Build web (project site base)
        run: |
          flutter build web --release --base-href /bou/
          # SPA 404 fix so deep links work
          cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true
